const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Behaviors.wrap,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.TileMovement.Acts.SetIgnoreInput,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.TextBox.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{cutscene: 0},
	{MovimentoEmGrid: 0},
	{CentrarEm: 0},
	{DarAVolta: 0},
	{Willian: 0},
	{Teclado: 0},
	{fundoPlantação: 0},
	{Sólido: 0},
	{RestritoAoLayout: 0},
	{chãoPlantação: 0},
	{casa: 0},
	{dialogo: 0},
	{linha_dialogo: 0},
	{falaNarrador: 0},
	{Intro3: 0},
	{cadeado: 0},
	{Toque: 0},
	{fundoBranco: 0},
	{Navegador: 0},
	{EntradaDeTexto: 0},
	{fundoCasa: 0},
	{bicicleta: 0},
	{mochila: 0},
	{estante: 0},
	{quadro: 0},
	{textoFase4: 0},
	{Intro4: 0},
	{fundoBiblioteca: 0},
	{mesa: 0},
	{secretaria: 0},
	{livros: 0},
	{gabarito: 0},
	{linhaDialogo: 0},
	{falaEsquerda: 0},
	{falaDireita: 0},
	{textoSecretaria: 0},
	{textoWilliam: 0},
	{textoFase1: 0},
	{next: 0},
	{Intro1: 0},
	{Sprite6: 0},
	{TextoGameOver: 0},
	{Sprite: 0},
	{TextoCongratulations: 0},
	{willianTriste: 0},
	{williamFeliz: 0}
];

self.InstanceType = {
	Willian: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	fundoPlantação: class extends self.ISpriteInstance {},
	chãoPlantação: class extends self.ISpriteInstance {},
	casa: class extends self.ISpriteInstance {},
	falaNarrador: class extends self.ISpriteInstance {},
	Intro3: class extends self.ITextInstance {},
	cadeado: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	fundoBranco: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	fundoCasa: class extends self.ISpriteInstance {},
	bicicleta: class extends self.ISpriteInstance {},
	mochila: class extends self.ISpriteInstance {},
	estante: class extends self.ISpriteInstance {},
	quadro: class extends self.ISpriteInstance {},
	textoFase4: class extends self.ITextInstance {},
	Intro4: class extends self.ITextInstance {},
	fundoBiblioteca: class extends self.ISpriteInstance {},
	mesa: class extends self.ISpriteInstance {},
	secretaria: class extends self.ISpriteInstance {},
	livros: class extends self.ISpriteInstance {},
	gabarito: class extends self.ISpriteInstance {},
	falaEsquerda: class extends self.ISpriteInstance {},
	falaDireita: class extends self.ISpriteInstance {},
	textoSecretaria: class extends self.ITextInstance {},
	textoWilliam: class extends self.ITextInstance {},
	textoFase1: class extends self.ITextInstance {},
	next: class extends self.ISpriteInstance {},
	Intro1: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TextoGameOver: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TextoCongratulations: class extends self.ITextInstance {},
	willianTriste: class extends self.ISpriteInstance {},
	williamFeliz: class extends self.ISpriteInstance {}
}